repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: mixed-line-ending

  - repo: local
    hooks:
      - id: r-lint
        name: Lint R files
        entry: Rscript -e 'if (requireNamespace("lintr", quietly = TRUE)) lintr::lint_dir("R")'
        language: system
        files: \.R$
        pass_filenames: false

